INSERT INTO Category (lbctgr) VALUES
('Abats'),
('Agrumes'),
('Algues'),
('Apéritifs et digestifs'),
('Autres'),
('Baies'),
('Barres chocolatés'),
('Base pour préparation'),
('Bières'),
('Biscuits'),
('Boissons'),
('Boissons alcoolisées'),
('Boissons plates'),
('Cacao'),
('Café'),
('Céréales'),
('Champignons'),
('Chocolat'),
('Choux'),
('Cidres'),
('Confiserie'),
('Confitures et marmelades'),
('Courges'),
('Dessert glacés'),
('Epicerie salée'),
('Epicerie sucrée'),
('Epices'),
('Farines et Levures'),
('Feuilles'),
('Fleurs'),
('Fromages'),
('Fromages à pâte demi-ferme'),
('Fromages à pâte dure'),
('Fromages à pâte ferme'),
('Fromages à pâte fraîche'),
('Fromages à pâte molle'),
('Fromages à pâtes persillées'),
('Fruits'),
('Fruits de mer'),
('Fruits secs'),
('Gâteaux et biscuits'),
('Herbes'),
('Huiles'),
('Insectes'),
('Jus de fruits'),
('Laitages et crémerie'),
('Légumes'),
('Légumes-fruits'),
('Légumes verts'),
('Légumineux'),
('Lentilles'),
('Miel'),
('Noix et graines'),
('Pains'),
('Pâtes'),
('Patisseries'),
('Plats Preparés'),
('Poissons'),
('Poissons blancs'),
('Poissons et crustacés'),
('Racines'),
('Riz'),
('Salades'),
('Sauces et assaisonnements'),
('Soda'),
('Sucre'),
('Thé'),
('Tubercules'),
('Viandes'),
('Viandes blanches'),
('Viandes rouges'),
('Vienoiseries'),
('Vins'),
('Volailles');
